### ISSUE TITLE
"value of type 'some View' has no member 'onGeometryChange'" error on iOS build in Github Action workflow

### ISSUE THREAD

**Issue by SamuelMereau** [software-mansion/react-native-gesture-handler#3505]
### Description

After updating Expo to SDK 53, react-native-gesture-handler has been throwing an error when attempting to build an iOS app via Github Actions.
This behaviour is different to when building locally, where no error is caught.

Error caught in build task:
```
[RUN_FASTLANE] › Packaging react-native-gesture-handler Pods/RNGestureHandler » libRNGestureHandler.a
[RUN_FASTLANE] 
❌  (node_modules/expo-modules-core/ios/Core/Views/SwiftUI/AutoSizingStack.swift:35:16)

  33 |             content.fixedSize(horizontal: axis.contains(.horizontal), vertical: axis.contains(.vertical))
  34 |               .hidden()
> 35 |               .onGeometryChange(for: CGSize.self, of: { proxy in proxy.size }, action: { size in
     |                ^ value of type 'some View' has no member 'onGeometryChange'
  36 |                 var size = size
  37 |                 size.width = axis.contains(.horizontal) ? size.width : ShadowNodeProxy.UNDEFINED_SIZE
  38 |                 size.height = axis.contains(.vertical) ? size.height : ShadowNodeProxy.UNDEFINED_SIZE

...

[RUN_FASTLANE] ** ARCHIVE FAILED **
[RUN_FASTLANE] The following build commands failed:
[RUN_FASTLANE] 	CompileSwift normal arm64 (in target 'ExpoModulesCore' from project 'Pods')

...

[RUN_FASTLANE] [!] Error building the application - see the log above
[RUN_FASTLANE] 
[RUN_FASTLANE] +--------------------------------------------+
[RUN_FASTLANE] |             Build environment              |
[RUN_FASTLANE] +-------------+------------------------------+
[RUN_FASTLANE] | xcode_path  | /Applications/Xcode_15.4.app |
[RUN_FASTLANE] | gym_version | 2.227.1                      |
[RUN_FASTLANE] | sdk         | iPhoneOS17.5.sdk             |
[RUN_FASTLANE] +-------------+------------------------------+
```

### Steps to reproduce

1. Create a fresh Expo SDK 53 app
```
$ bun x create-expo-app@latest GestureHandlerRepro
$ cd ./GestureHandlerRepro
$ bun run reset-project
$ bun x expo prebuild -p ios
```
2. Set up a repository with the Github action workflow below, ensuring secrets are filled to allow building. In this example, I am using Bun to bundle the app however NPM and Yarn will also produce the same result.
```
name: Build iOS App

on:
  push :
    branches : [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4      
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          packager: bun
          expo-cache: false
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install Dependencies
        run: bun install
        
      - name: Build iOS App
        run: eas build --local -p ios --profile production --non-interactive --output app.ipa
```
3. Push an initial commit to the repository, to fire the workflow event.

### Snack or a link to a repository

https://github.com/SamuelMereau/react-native-gesture-handler-workflow-repro/

### Gesture Handler version

2.24.0, 2.25.0

### React Native version

0.79.2

### Platforms

iOS

### JavaScript runtime

Hermes

### Workflow

Expo bare workflow

### Architecture

Fabric (New Architecture)

### Build type

Release mode

### Device

iOS simulator

### Device model

iPhoneOS17.5 running in the cloud (as a Github Workflow)

### Acknowledgements

Yes
